<template>
    <div class="scene-01-container">
        <PolygonjsScene
            :loadFunction="loadFunction"
            :sceneName="'scene_01'"
            @sceneready='onSceneReady'
            />
        <div class="buttons disable-select">
            <span class="button" @click='decrement'><svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
  <path stroke-linecap="round" stroke-linejoin="round" d="M15 12H9m12 0a9 9 0 11-18 0 9 9 0 0118 0z" />
</svg></span>
            <span class="button" @click='increment'><svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
  <path stroke-linecap="round" stroke-linejoin="round" d="M12 9v3m0 0v3m0-3h3m-3 0H9m12 0a9 9 0 11-18 0 9 9 0 0118 0z" />
</svg></span>
        </div>
    </div>
</template>

<script lang="ts">
import { defineComponent, ref, watch,computed } from "vue";
import { PolygonjsScene } from "@polygonjs/vue3";
import { loadScene_scene_01 } from "@/polygonjs/scenes/scene_01/autogenerated/loadScene";
import { PolySceneWithNodeMap_scene_01 } from "@/polygonjs/scenes/scene_01/autogenerated/PolySceneWithNodeMap";

export default defineComponent({
  name: "scene-01",
  components: {
    PolygonjsScene,
  },
  setup() {
      let scene: PolySceneWithNodeMap_scene_01|undefined
      const count = ref(10)
      function increment(){
          count.value++
      }
      function decrement(){
          count.value--
      }
      watch(count, updateCount);
      function updateCount(){
          if(!scene){return}
          scene.node('/geo1/copy1').p.count.set(count.value)
      }


      function onSceneReady(loadedScene: PolySceneWithNodeMap_scene_01){
          scene = loadedScene;
          updateCount()
      }
      const loadFunction = computed(()=>loadScene_scene_01)

    return {
      loadFunction,
      onSceneReady,
      increment,
      decrement
    };
  },
});
</script>

<style>
.scene-01-container {
    position: relative;
}
.buttons {
    position: absolute;
    top: 0px;
    left: 0px;
    padding: 10px;
    width: 100%;
    pointer-events: none;
}
.buttons .button {
    cursor: pointer;
    pointer-events: auto;
    padding: 5px 10px;
    font-size: 1.6rem;
    background-color: white;
    border-radius: 3px;
    display: inline-block;
    width: 60px;
    position: relative;
    top: 0px;
    margin-left: 2px;
}
.buttons .button:active {
    top: 2px;
}
.buttons .button svg {
    line-height: 0px;
    margin: 0px;
    display: block;
}
.disable-select {
	user-select: none;
	-webkit-user-select: none;
	-khtml-user-select: none;
	-moz-user-select: none;
	-ms-user-select: none;
}
</style>