<template>
    <div class="scene-02-container">
        <PolygonjsScene
            :loadFunction="loadFunction"
            :sceneName="'scene_02'"
            @sceneready='onSceneReady'
            />
         <div class="controls disable-select">
             <input type="range" min="0.1" max="0.6" step="0.01" v-model="size"/>
         </div>
    </div>
</template>

<script lang="ts">
import { defineComponent, ref, watch, computed } from "vue";
import { PolygonjsScene } from "@polygonjs/vue3";
import { loadScene_scene_02 } from "@/polygonjs/scenes/scene_02/autogenerated/loadScene";
import { PolySceneWithNodeMap_scene_02 } from "@/polygonjs/scenes/scene_02/autogenerated/PolySceneWithNodeMap";

export default defineComponent({
  name: "scene-02",
  components: {
    PolygonjsScene,
  },
  setup() {
      let scene: PolySceneWithNodeMap_scene_02|undefined
      const size = ref(0.2)

       watch(size, updateSize);
      function updateSize(){
          if(!scene){
              return
            }
          scene.node('/rhino/fuse1').p.dist.set(size.value);
      }

      function onSceneReady(loadedScene: PolySceneWithNodeMap_scene_02){
          scene = loadedScene;
          updateSize();
      }
      const loadFunction = computed(()=>loadScene_scene_02)
    return {
      loadFunction,
      onSceneReady,
      size
    };
  },
});
</script>

<style scoped>
.scene-02-container {
    position: relative;
}
.controls {
    position: absolute;
    top: 0px;
    left: 0px;
    padding: 10px;
    width: 100%;
    pointer-events: none;
}
.controls input {
    pointer-events: auto;
    width: 95%;
}

.disable-select {
	user-select: none;
	-webkit-user-select: none;
	-khtml-user-select: none;
	-moz-user-select: none;
	-ms-user-select: none;
}
</style>