<template>
    <PolygonjsScene :loadFunction="loadFunction"/>
</template>

<script lang="ts">
import { defineComponent } from "vue";
import { PolygonjsScene } from "@polygonjs/vue3";
import { loadSceneAndMountAsync_scene_03 } from "@/polygonjs/scenes/scene_03/autogenerated/loadSceneAndMountAsync";

export default defineComponent({
  name: "scene-03",
  components: {
    PolygonjsScene,
  },
  setup() {
    return {
      loadFunction: loadSceneAndMountAsync_scene_03,
    };
  },
});
</script>
