<template>
    <PolygonjsScene
      :loadFunction="loadFunction"
      :sceneName="'scene_03'"
    />
</template>

<script lang="ts">
import { defineComponent, computed } from "vue";
import { PolygonjsScene } from "@polygonjs/vue3";
import { fetchSceneAndMount_scene_03 } from "@/polygonjs/scenes/scene_03/autogenerated/fetchSceneAndMount";

export default defineComponent({
  name: "scene-03",
  components: {
    PolygonjsScene,
  },
  setup() {
    const loadFunction = computed(()=>fetchSceneAndMount_scene_03)
    return {
      loadFunction,
    };
  },
});
</script>
